using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Quaternion_Rotate_ALL : MonoBehaviour
{
    public Transform target;
    public float lerpSpeed = 0.5f;

    private Quaternion startRotation;
    private Quaternion targetRotation;

    private void Start()
    {
        // Υ嫫鹗嘉恢煤湍宋恢玫男D值
        startRotation = transform.rotation;
        targetRotation = target.rotation;
    }

    private void Update()
    {
        // 在起始和目酥gM行插值
        Quaternion newRotation = Quaternion.Lerp(startRotation, targetRotation, lerpSpeed * Time.deltaTime);

        // ⑿碌男D值用到物件上
        transform.rotation = newRotation;
    }
}
